"""
Commenting skills:

TODO: above every line of code comment what you THINK the line below does.
TODO: execute that line and write what actually happened next to it.

See example for first print statement
"""
import platform

# I think this will print "hello! Let's get started" by calling the print function.
print("hello! Let's get started")  # it printed "hello! Let's get started"

# Assigns list values (words and symbol) to the variable name "some_words"
some_words = ['what', 'does', 'this', 'line', 'do', '?']

# Generates an iterator ("word") from the list values assigned to the variable name "some_words"
for word in some_words:
    print(word) # Then prints the results generated by the iterator

# Generates an iterator ("x") from the same list values assigned to the variable name "some_words"
for x in some_words:
    print(x) # Then prints the results generated by the interator

# Prints the list values assigned to the variable name "some_words"
print(some_words)

# Generates a conditional statement to test the validity of an expression
if len(some_words) > 3:
    print('some_words contains more than 3 words') # Then prints an output if the conditional statement is satisfied

# Defines a function to print an identifying data
def usefulFunction():
    """
    You may want to look up what uname does before you guess
    what the line below does:
    https://docs.python.org/3/library/platform.html#platform.uname
    """
    print(platform.uname()) # Access to underlying platform's identifying data is displayed once the function is called.

# The custom function (as defined above) is called
usefulFunction()
